### ISSUE TITLE
Category list UI alignmnet

### ISSUE THREAD

**Issue by vishnuvnathan** [navafmuhammed/designcrate#2]
![Screenshot from 2023-04-29 18-02-05](https://user-images.githubusercontent.com/16370789/235303033-c6dcca23-5a5d-410d-a0bd-718d73ce8c5f.png)

**Comment by navafmuhammed** [comment]
Fixed
![image](https://user-images.githubusercontent.com/34545668/235652035-4b1da885-de43-42f9-9df9-8418e97167e0.png)
