### ISSUE TITLE
Category chip over flow on screen width 990px to 768px

### ISSUE THREAD

**Issue by vishnuvnathan** [navafmuhammed/designcrate#4]
![Screenshot from 2023-04-29 18-08-13](https://user-images.githubusercontent.com/16370789/235302967-d256aaf5-6b6b-47d9-8d38-2e80ed61a9a2.png)

**Comment by navafmuhammed** [comment]
![navafmuhammed github io_designcrate_](https://user-images.githubusercontent.com/34545668/235852640-84c6682a-e002-48d8-b548-19ead6bf7ea2.png)
